### PR TITLE
UNTESTED: Add possibility to get schema from a graphql server

### PR DESCRIPTION
**Pull request by Justkant**
Hi,

I push this pull request to know first if this is useful and if I can get a good reply from you, I will update the README.md. 

TODO: update README.md & tests

### CODE REVIEW

**Comment by BerndWessels** [comment]
Hi @Justkant 
Looks good to me. To be honest, I can't think about a situation for my own projects where I would receive the schema from an URL, but I believe that there are good reasons to do so.
Once you have tested it thoroughly and added documentation, please let me know and I can pull it.
I you are keen I can make you a collaborator as well.
Cheers
Bernd

**Comment by Justkant** [comment]
Hi again,

I'll do the rest tonight I think. And to clarify my situation, I have a separate API repo and I didn't wanted to copie the schema each time I change the API.
I'll be happy to become a collaborator.
Cheers

**Comment by BerndWessels** [comment]
Great, thanks for that.
Master is now for `babel-relay-plugin` `0.7.0`.
I made you a collaborator.
Cheers
Bernd

**Comment by Justkant** [comment]
I don't think that my pull request is useful after some tweak on my side.
I post here my solution with `babel-relay-plugin`.

On the API side:

``` javascript
app.get('/schema', function (req, res) {
  graphql(schema, introspectionQuery).then(function (schema) {
    res.json(schema).end()
  }, function (err) {
    res.status(400).json(err.errors).end()
  }
})
```

On the App side:

My `.babelrc`:

```
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["./tools/babelRelayPlugin"]
}
```

The `tools/babelRelayPlugin.js`:

``` javascript
var getBabelRelayPlugin = require('babel-relay-plugin')
var request = require('sync-request')

var response = request('GET', 'http://localhost:3030/schema')

var schema = JSON.parse(response.getBody('utf-8'))

module.exports = getBabelRelayPlugin(schema.data)
```

**Pull request closed without merging**
