### PR TITLE
Remove console logging which was printing to file.

### PR DESCRIPTION
**Pull request by dardub**
Console logs were outputting to compiled js file.

### CODE REVIEW

**Comment by BerndWessels** [comment]
Hi @dardub .

I don't mind pulling your request, just wondering why you don't like the log? I actually find it very helpful.

Cheers
Bernd

**Comment by dardub** [comment]
Maybe my setup is wrong, but when my js files are bundled, the output of the log is added to the top of my concatenated js file resulting in a syntax error. Like the following:

`babel-relay-plugin-loader: using schema at [/Users/foo/Sites/relay-blog/app/assets/javascripts/relay/schema.json]
;
(function() {
  window.App || (window.App = {});
`

So I was worried others may experience the same issue.

**Comment by BerndWessels** [comment]
@dardub Can you share your build process? I haven't heard anybody experiencing this.
It would be actually very odd if a `console.log` output would make it into the compiled code. But everything is possible I guess. Let's checkout your build setup first to see what is really happening here.
Cheers
Bernd

**Comment by BerndWessels** [comment]
Hi @dardub 
I am closing this for now since nobody else seem to have a problem with it.
Let me know if you keep having the problem and share some code to reproduce, we can reopen it then.
Cheers
Bernd

**Pull request closed without merging**
