### PR TITLE
babel-relay-plugin 0.4.1

### PR DESCRIPTION
**Pull request by idris**

### CODE REVIEW

**Comment by BerndWessels** [comment]
@idris Thanks, I merged it and published it to npm.

**Comment by idris** [comment]
@BerndWessels I think the npm publish may not have worked? Or maybe npm has it cached?

**Comment by BerndWessels** [comment]
@idris Oops, might ended up in my private registry. Should be published properly now. Can you please try?
I also added you as a collaborator, since I might not always be able to react in an acceptable time span.
I wonder if there is a way to share the right to publish a package to npm too?

**Comment by BerndWessels** [comment]
Oh I see.
`npm owner add <user> [<@scope>/]<pkg>`
`add: Add a new user as a maintainer of a package. This user is enabled to modify metadata, publish new versions, and add other owners.`
@idris When you tell me your npm user I can add you to the owner of this package and you can also publish it yourself if I am not available.

**Comment by idris** [comment]
@BerndWessels Thanks!  My npm username is `idris`

**Comment by BerndWessels** [comment]
@idris OK, I've added you like this:

`npm owner add idris babel-relay-plugin-loader`

which returned

`+ idris (babel-relay-plugin-loader)`

So you should be able in future to update the Git Repo and publish to NPM if I am not available.

Thanks again for colaborating.

**Pull request merged**
