### PR TITLE
Use template string rather than concatenation.

### PR DESCRIPTION
**Pull request by robbyoconnor**
This was causing an error, plus this is a cleaner way.

### CODE REVIEW

**Comment by BerndWessels** [comment]
Thank for the PR, I pulled it already to master. Let me know if you want that published to NPM, otherwise I will just wait until the next version increase of `babel-relay-plugin` since I try to keep them in sync (and now realize that synchronized version numbers are maybe not really working so well).
Cheers
Bernd

**Comment by robbyoconnor** [comment]
I'm not using it anymore so I don't have a preference

--Rob

**Comment by BerndWessels** [comment]
ok, no worries - `0.7.1` just released, so will publish it now.

If you are not using it anymore - does that mean there is a way now without the loader to use `babel-relay-plugin` ?

Cheers
Bernd

**Comment by robbyoconnor** [comment]
I mean I have no use for it period

--Rob

**Comment by BerndWessels** [comment]
OK ;)

**Comment by robbyoconnor** [comment]
Using it again Why would this cause an error?

**Comment by BerndWessels** [comment]
@robbyoconnor  sorry what?

I pulled and released it as part of the `0.7.1` release. It seems to work just fine.

**Comment by robbyoconnor** [comment]
Was PEBKAC, nevermind.

**Comment by robbyoconnor** [comment]
@BerndWessels, 

```
[stdin]:1
babel-relay-plugin-loader: using schema at [redacted]
                         ^

SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:413:34)
    at node.js:612:27
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

This running with the latest

**Comment by BerndWessels** [comment]
Hi @robbyoconnor 
I don't get any errors with the latest `0.7.1`.
Maybe your `.babelrc` is missing something.
Can you compare yours with this one please:

```
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "env": {
    "development": {
      "plugins": [
        "babel-relay-plugin-loader",
        [
          "react-transform",
          {
            "transforms": [
              {
                "transform": "react-transform-hmr",
                "imports": [
                  "react"
                ],
                "locals": [
                  "module"
                ]
              },
              {
                "transform": "react-transform-catch-errors",
                "imports": [
                  "react",
                  "redbox-react"
                ]
              }
            ]
          }
        ],
        [
          "react-intl",
          {
            "messagesDir": "./build/i18n/",
            "enforceDescriptions": true
          }
        ]
      ]
    },
    "production": {
      "plugins": [
        "babel-relay-plugin-loader"
      ]
    }
  }
}
```

If that's not the problem, maybe share a bit more of your project to reproduce the bug.

Thanks
Bernd

**Comment by robbyoconnor** [comment]
Commenting out the console.log fixes the problem

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67oey-y5&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=RVaaqZ3E&invitationId=6130897050591645696








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67oey-y5&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGHUS0LSElMMQAAAVRVScFrF_TafeV_zjmY9hsof22SYYiaiqgh2zC4dqucXxrtFJ8XT53NfmuoBZ97uRHbam2msrHhFFEdM_rMRrWVifRt9EKIPVZHuIYb9Mmkzq0hbA0R5lFcrvuQag-BaqDKzfbNpUp9LWQKcls-2v9FscrvQGzY4J0aMYgxWEjrnnNvmga4&eid=0-ini67oey-y5


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67oey-y5&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
